export const data = [
    {
        id:1,
        empName:"Seema",
        qualification:"MCA",
        salary:10000,
        department:'Coding'
    },
    {
        id:2,
        empName:"Seema1",
        qualification:"MCA",
        salary:10000,
        department:'Coding'
    },
    {
        id:3,
        empName:"Seema2",
        qualification:"BCA",
        salary:20000,
        department:'Coding'
    },
    {
        id:4,
        empName:"Seema3",
        qualification:"MCA",
        salary:10000,
        department:'Coding'
    },
    {
        id:5,
        empName:"Seema4",
        qualification:"MCA",
        salary:10000,
        department:'Coding'
    },
]